<?
$GLOBALS['_STRINGS']['backend']=array(
BACKEND_CARTRIDGE=>"System backend",
ADMIN_INACTIVECARTRIDGE=>"Cartridge is blocked",
ADMIN_CONTROLSAVAILABLE=>"Page elements that can be used",
MENUCATEGORY_VIEW=>"View",
MENUCATEGORY_ADMIN=>"Administration",
MENUCATEGORY_CONTENT=>"Content",
MENUCATEGORY_TOOLS=>"Tools",


ROLE_BACKENDACCESS=>"Working with administrative panel",
ROLE_BACKUPMANAGER=>"Site backup manager",
ROLE_CHANGE_SETTINGS=>"Can change settings",
ROLE_CHANGE_CONFIG=>"Can change site config and htaccess",

TITLE_BACKUPSYSTEM=>"Website backup system",
TITLE_LOGINFORM=>"Entering the system",
TITLE_SETTINGS=>"Settings",
TITLE_FRONTDOORS=>"Frontdoors",

CAPTION_LOGOUT=>"Logout",
CAPTION_LOGIN=>"Login",
CAPTION_PASSWORD=>"Password",
CAPTION_ENTER=>"Enter",
CAPTION_LANGUAGE=>"Language",
LINK_FORGETPASSWORD=>"Forgot your password?",
LINK_SHOWSECURITYINFO=>"Show security information",

TITLE_DO_REMEMBER=>"Password reminder",
MSG_DO_REMEMBER=>"Enter your login for receiving the password by email",
CAPTION_SENDPASSWORD=>"Send the password",
MSG_INCORRECT_LOGIN=>"Invalid login or password. Try again",
LOGGED_OUT=>"You left the system",
REMEMBER_MAIL_SUBJECT=>"Password reminder",
REMEMBER_MAIL_TEXT=>"Reminding you the password for accessing the site",
REMEMBER_MAIL_SENT=>"The reminder has been sent to your email",

BACKEND_PERMITTED_FOR_YOU=>"Site management is blocked for this account. Enter another password for accessing the system",
KEEP_SESSION_LOCKED=>"Remember the password",
ERROR_COOKIE=>"Attention! Your internet browser does not support cookies. You cannot operate in administration module. Switch on this option in your web browser!",
ERROR_COOKIEPATH=>"Error! Session variables duplicates. Check out path or clear cookie in browser",
SETTINGS_UPDATED=>"Setting are updated",

BACKUP_CHOOSE_TABLES=>"Choose tables to backup",
BACKUP_SELECT_ALL_TABLES=>"Select all tables",
BACKUP_VIEW_SELECTED_TABLES=>"View selected tables and deselect any",
BACKUP_THESE_TABLES=>"Backup these tables",
BACKUP_DESCRIPTION=>"Description",
BACKUP_EXISTING_BACKUPS=>"Backup files on the server",
BACKUP_NEW_FILENAME=>"New backup file name",
BACKUP_FILE=>"Backup file",
BACKUP_ROWCOUNT=>"Row count",
BACKUP_PACKUNPACK_SIZE=>"packed/unpacked size",
BACKUP_DATE=>"Backup date",
BACKUP_TABLECOUNT=>"Table count",
BACKUP_SELECT_TABLES_TO_RESTORE=>"Select tables to restore",
BACKUP_RESTORE_WARNING=>"After restoring database you may lose connection to the system. To prevent this do not restore table um_Sessions",
BACKUP_COMPLETE=>"Backup complete. File is successfully saved",
BACKUP_CAPTION_RESTORE=>"Restore selected",
BACKUP_CAPTION_PREVIEW=>"Preview",
BACKUP_ZIP_TOTAL=>"Total size of all zip files",
BACKUP_REMOVING_TITLE=>"Removing of database backup jsbz-files",
BACKUP_NO_SELECTION=>"No one backup has been selected",
BACKUP_REMOVE_PROTECTED=>"Can't remove. Skipped",
BACKUP_FILENOTFOUND=>"File not found. Skipped",
BACKUP_FILEREMOVED=>"Removed",

BACKUPRESOURCE_PHPSBSCRIPTS=>"PHPSB current version scripts",
BACKUPRESOURCE_SELECT=>"Select file resources that should be backup:",
BACKUPRESOURCE_FILES=>"Uploaded images, files and richtext content",
BACKUPRESOURCE_SCRIPTS=>"Website local cartridges scripts",
BACKUPRESOURCE_DATA=>"Log files and settings",
BACKUPRESOURCE_PUBLIC=>"Javascript public files and system icons",
BACKUPRESOURCE_THEMES_SKINS=>"Site skins and themes",
BACKUPRESOURCE_ROOT_CONFIG=>"Root folder files (all but config file)",
BACKUPRESOURCE_OTHER=>"Other folders presents in the site (without backups and tmp)",
BACKUPRESOURCE_ADVANCED_SELECT=>"Advanced resources. Scripts and other files that should be restored carefully:",
BACKUPRESOURCE_EXCLUDEEXT=>"Exclude files with extensions (comma-separated list)",

CAPTION_PAGE_MENUCAPTION=>"Menu item caption",
CAPTION_CALLINTERFACEMETHOD=>"Calling interface method",
CAPTION_EDITADMINMENU=>"Customize top menu",

SET_BACKEND_SKIN=>"Set backend panel skin",

FRONTDOORS=>"Frontdoors",
DOORKEEPERS=>"Door keepers",
ADD_NEW_FRONTDOOR=>"Add a new frontdoor",
ADD_NEW_DOORKEEPER=>"Add a new door keeper",
BROWSER_LANGUAGES=>"Languages of a client browser",
OPENING_DOOR=>"Opening door",
);


?>
