<?
$GLOBALS[_STRINGS][backend]=array(
BACKEND_CARTRIDGE=>"Административная панель",
ADMIN_INACTIVECARTRIDGE=>"Картридж заблокирован",
ADMIN_CONTROLSAVAILABLE=>"Элементы страниц, которые могут быть использованы",
MENUCATEGORY_VIEW=>"Вид панели",
MENUCATEGORY_ADMIN=>"Администрирование",
MENUCATEGORY_CONTENT=>"Контент",
MENUCATEGORY_TOOLS=>"Инструменты",

ROLE_BACKENDACCESS=>"Доступ к административной панели",
ROLE_BACKUPMANAGER=>"Менеджер резервного копирования сайта",
ROLE_CHANGE_SETTINGS=>"Может менять настройки сайта",
ROLE_CHANGE_CONFIG=>"Может вносить изменения в конфиг и htaccess",

TITLE_BACKUPSYSTEM=>"Резервирование вебсайта",
TITLE_LOGINFORM=>"Вход в систему",
TITLE_SETTINGS=>"Установки",
TITLE_FRONTDOORS=>"Фронтдоры (парадные двери) сайта",

CAPTION_LOGOUT=>"Выйти из системы",
CAPTION_LOGIN=>"Логин",
CAPTION_PASSWORD=>"Пароль",
CAPTION_ENTER=>"Войти",
CAPTION_LANGUAGE=>"Язык",
LINK_FORGETPASSWORD=>"Забыли пароль?",
LINK_SHOWSECURITYINFO=>"Показать параметры безопасности",

TITLE_DO_REMEMBER=>"Напоминание пароля",
MSG_DO_REMEMBER=>"Введите свой логин и на ваш E-mail будет отправлен пароль",
CAPTION_SENDPASSWORD=>"Отправить пароль",
MSG_INCORRECT_LOGIN=>"Неправильный логин или пароль. Попробуйте еще раз",
LOGGED_OUT=>"Вы покинули систему",
REMEMBER_MAIL_SUBJECT=>"Напоминание о пароле",
REMEMBER_MAIL_TEXT=>"Напоминаем вам пароль для доступа на сайт",
REMEMBER_MAIL_SENT=>"Напоминание отправлено на ваш Email",

BACKEND_PERMITTED_FOR_YOU=>"Управление сайтом закрыто для указанного аккаунта. Введите другой пароль для доступа к системе",
KEEP_SESSION_LOCKED=>"Запомнить пароль",
ERROR_COOKIE=>"Внимание! Ваша система не поддерживает cookie. Вход в систему администрирования невозможен! Включите cookie в броузере",
ERROR_COOKIEPATH=>"Оишбка! Дублирование переменных cookie. Проверьте путь или удалите cookie в своем броузере",
SETTINGS_UPDATED=>"Установки сохранены",

BACKUP_CHOOSE_TABLES=>"Выберите таблицы для бэкапа",
BACKUP_SELECT_ALL_TABLES=>"Выбрать все таблицы",
BACKUP_VIEW_SELECTED_TABLES=>"Показать выбранные таблицы и снять отметку с некоторых",
BACKUP_THESE_TABLES=>"Создать бэкап",
BACKUP_DESCRIPTION=>"Описание бэкапа",
BACKUP_EXISTING_BACKUPS=>"Бэкапы, хранящиеся сейчас на сервере",
BACKUP_NEW_FILENAME=>"Название создаваемого файла",
BACKUP_FILE=>"Файл бэкапа",
BACKUP_ROWCOUNT=>"К-во строк",
BACKUP_PACKUNPACK_SIZE=>"Упакованный/Исходный размер",
BACKUP_DATE=>"Дата создания",
BACKUP_TABLECOUNT=>"Кол-во таблиц",
BACKUP_SELECT_TABLES_TO_RESTORE=>"Выберите таблицы для восстановления из бэкапа",
BACKUP_RESTORE_WARNING=>"Внимание! После того как данные будут восстановлены вы можете утерять соединение с системой. Если вы не хотите этого - не выделяйте таблицу um_Sessions",
BACKUP_COMPLETE=>"Файл бэкапа сохранен",
BACKUP_CAPTION_RESTORE=>"Распаковать выделенные",
BACKUP_CAPTION_PREVIEW=>"Посмотреть",
BACKUP_ZIP_TOTAL=>"Общий размер jsbz-файлов",
BACKUP_REMOVING_TITLE=>"Удаление бэкапов базы данных",
BACKUP_NO_SELECTION=>"Не было выбрано ни одного файла бэкапа",
BACKUP_REMOVE_PROTECTED=>"Файл не удаляется. Пропускаю",
BACKUP_FILENOTFOUND=>"Файл не найден. Пропускаю",
BACKUP_FILEREMOVED=>"Удален",

BACKUPRESOURCE_PHPSBSCRIPTS=>"Программное ядро PHPSB",
BACKUPRESOURCE_SELECT=>"Выберите файловые ресурсы, которые будут также сохранены",
BACKUPRESOURCE_FILES=>"Изображения, содержание текстовых элементов, файлы пользователей",
BACKUPRESOURCE_SCRIPTS=>"Локальные картриджи сайта (программы)",
BACKUPRESOURCE_PUBLIC=>"Файлы Javascript и системные иконки",
BACKUPRESOURCE_DATA=>"Настройки сайта и его логи",
BACKUPRESOURCE_THEMES_SKINS=>"Версии тем сайта и их дизайн",
BACKUPRESOURCE_ROOT_CONFIG=>"Файлы, присутствующие в корневой папке сайта (кроме inc.config.php)",
BACKUPRESOURCE_OTHER=>"Содержимое других папок сайта (кроме backups и tmp)",
BACKUPRESOURCE_EXCLUDEEXT=>"Исключить файлы с расширениями (перечислите через запятую)",

CAPTION_PAGE_MENUCAPTION=>"Надпись элемента меню",
CAPTION_CALLINTERFACEMETHOD=>"Вызываемое действие",
CAPTION_EDITADMINMENU=>"Настройка административного меню",

SET_BACKEND_SKIN=>"Настройка вида панели управления",

FRONTDOORS=>"Фронтдоры (входные двери сайта)",
DOORKEEPERS=>"Привратники",
ADD_NEW_DOORKEEPER=>"Добавить привратника",
ADD_NEW_FRONTDOOR=>"Добавить фронтдор",
BROWSER_LANGUAGES=>"Языки используемые броузером посетителя",
OPENING_DOOR=>"Какую дверь открыть",
);

?>
