<?
$GLOBALS['_STRINGS']['news']=array(

NEWS_CARTRIDGETITLE=>"News publishing",
CAPTION_BROWSE_GROUPS=>"Overview news",
CAPTION_EDIT_GROUPS=>"Edit news groups",
CAPTION_NEWS_SETTING=>"News publisher settings",
ROLE_POSTNEWS=>"News posting",
ROLE_REMOVENEWS=>"News removal",
ROLE_CHANGESETTINGS=>"Changing news publisher settings",
ROLE_NEWSBACKEND=>"News editing system access",

BACKEND_NEWS_BRIEF_CONTENT=>"News contents",


ERROR_UNKNOWNGROUP=>"No such group",
MSG_INVALID_TARGET_USER=> "User with %s identifier is absent",
TITLE_INSERTNEWS=>"Adding news piece",
TITLE_EDITNEWS=>"News piece editing",

MSG_OPTIONS_UPDATED=>"Settings have been changed",
TITLE_NEWS_SETTINGS=>"News module settings",
WARNING_SAVEMEFIRST=>"Save the news before you can edit the full news text and add pictures to it",
HEADIMAGE=>"News heading image",
TITLE_IMAGEINDEX=>"News album images",
TITLE_RICHTEXT=>"Full news text",
PRESENT_DATE=>"Current news",
FUTURE_DATE=>"Too early to publish",
PAST_DATE=>"Outdated",
EDIT_GROUPS_TEXT=>"Below is the window of news management. Press (+) to unfold the groups.To add a new group righclick the group name and select 'Add page'. ",

TNEWSEVENT_ABOUT=>"The element for loading and displaying the news",

TNEWSEVENT_P_CSS_TITLE=>"Title style",
TNEWSEVENT_P_CSS_DATE=>"Date text style",
TNEWSEVENT_P_CSS_AUTHOR=>"Author name text displaying style",
TNEWSEVENT_P_CSS_INTRO=>"Intro style",
TNEWSEVENT_P_SHOWDATE=>"Display date",
TNEWSEVENT_P_HIDEALLTEXT=>"Do not display text contents, just load",
TNEWSEVENT_P_HIDEIMAGE=>"Do not display image",
TNEWSEVENT_P_HIDEAUTHOR=>"Do not display author",

TNEWSEVENT_D_THENEWSEVENT=>"News event",
TNEWSEVENT_D_THENEWSGROUP=>"News group",
TNEWSEVENT_D_TITLE=>"News title",
TNEWSEVENT_D_BODY=>"Full news text",
TNEWSEVENT_D_INTRO=>"Intro text",
TNEWSEVENT_D_SUBJECT=>"Subject:",

TNEWSEVENT_PLACED_IN_LAYOUT=>"News piece will be here. You will see the contentsof this element only when viewing pages in this style",
TNEWSEVENT_D_DATE=>"Event date",
TNEWSEVENT_D_AUTHOR=>"Text author",
TNEWSEVENT_D_DATETOSHOW=>"News publishing date",
TNEWSEVENT_D_DATETOHIDE=>"News hiding date",
NEWSBROWSER_P_NEWSGROUP=>"Display news for selected group only",
NEWS_TN_FORMAT=>"Thumbnail format",

NEWS_PHOTO=>"News image",
MONTHS_AGO=>"months ago",
ADD_NEW_EVENT=>"Add new event",
EVENT_WITHOUT_TITLE=>"(no title)",
EVENT_WITHOUT_INTRO=>"News without intro. When viewing news lists, the subject of this news piece will be unclear",
WILL_BE_HREF_TO=>"Open a http address instead of news opening:",
ATTACH_FILE=>"Attach a file",
INTRO=>"Short intro",
TITLE=>"Title",
REMOVE_PHOTO=>"Remove image",
REMOVE_ATTACHMENT=>"Remove file",
ONLY_JPEG_ACCEPTED=>"(indicate jpeg file)",
BODY=>"Full news text",
AUTHOR=>"Author/source",
AUTHOR_HTTP=>"Source web-site",
SAMPLE_NEWS_INTRO=>"This a news text sample that can be published in a page element.
Actual news piece text can be times larger that this sample",
SAMPLE_NEWS_TITLE=>"News title sample",
NO_NEWS_EVENTS=>"No news",
EVENTS_OF_A_DATE=>"News for ",
ALL_DATES_EVENTS=>"All dates events",
NEWSDATEFORMAT=>"Date displaying format",
KEYWORDS=>"Key words",

PUBSTATUS=>"Publication status",
PUBSTATUS_0=>"Under review (hidden)",
PUBSTATUS_5=>"Additional editing needed",
PUBSTATUS_10=>"Published",


NEWSGROUP_CAPTION=>"Current news group caption",
NEWSGROUP_SUPERCAPTION=>"Parent news group caption",
NEWSGROUP_TARGET_NEWSEVENTS_CONTEXT=>"System context diplaying news",

NEWSBROWSER_C_MORE=>"more news...",
NEWSBROWSER_C_DETAILS=>"details...",
NEWSBROWSER_C_PAGES=>"pages: ",
NEWSBROWSER_P_INTROLENGTH=>"Max intro size in characters",
NEWSBROWSER_P_EVENTSPERPAGE=>"Number of news per page",
NEWSBROWSER_BIND_TO_THIS_PAGE=>"Display the current page news",
NEWSBROWSER_GROUP_NAME_SAMPLE=>"Current news group title",
NEWSBROWSER_SAMPLELIST=>"News titles will be displayed here",
NEWSBROWSER_P_SHOWBODYASHREF=>"Short description of of the news will be be used a link to news 'details'",
NEWSBROWSER_P_GROUPFROMEVENT=>"Indicate the element to publish the news or the news group",
NEWSBROWSER_SHOWONERANDOM=>"Show only one random event",
NEWSBROWSER_CHECKFORDETAILS=>"Check existance of details of the news event. It is add one query to database",
NEWSBROWSER_PAGES=>"Pages of news",

MOVE_NEWS_TO=>"Move to ",
TNEWSPATH_ABOUT=>"Types the path to the news loaded as links to parent news groups",
TNEWSPATH_ATTACHROOT=>"Attach a new website branch",

TLASTEVENT_ABOUT=>"Last news in the list",

TNEWSBROWSER_CAPTION=>'Prints news headlines',
TNEWSBROWSER_DESCRIPTION=>'Prints one page of news list. Each news contains date, title, short description and image.',
TNEWSEVENT_CAPTION=>'News event reader',
TNEWSEVENT_DESCRIPTION=>'Publish news event data to the page. The TText control will print this information. The TImage contrl will shows event photo. The TImgIndex control will shows photo gallery of event',
SETTING_MONTHSTOSHOW=>'How much months the article will be shown in list as default',
NEWSLIST_VIEW=>"News list view",
WEBSITE_VIEW=>"Website view",

);
?>
