<?
$GLOBALS['_STRINGS']['news']=array(
NEWS_CARTRIDGETITLE=>"Новости",
CAPTION_BROWSE_GROUPS=>"Новости",
CAPTION_EDIT_GROUPS=>"Настройка новостей",
CAPTION_NEWS_SETTING=>"Настройки отображения новостей",
ROLE_POSTNEWS=>"Создание новостей",
ROLE_REMOVENEWS=>"Удаление новостей",
ROLE_CHANGESETTINGS=>"Изменение настроек публикатора",
ROLE_NEWSBACKEND=>"Доступ к системе редактирования новостей",
BACKEND_NEWS_BRIEF_CONTENT=>"Содержание новости",

ERROR_UNKNOWNGROUP=>"Нет такой группы",
MSG_INVALID_TARGET_USER=> "Пользователь с идентификатором %s отсутствует",
TITLE_INSERTNEWS=>"Добавление новости",
TITLE_EDITNEWS=>"Редактирование новости",

MSG_OPTIONS_UPDATED=>"Настройки изменены",
TITLE_NEWS_SETTINGS=>"Настройки модуля новостей",
WARNING_SAVEMEFIRST=>"Сначала сохраните новость, затем Вы сможете редактировать полный текст статьи и добавлять фотографии к ней",
HEADIMAGE=>"Фотография шапки новости",
TITLE_IMAGEINDEX=>"Фотоальбом",
TITLE_RICHTEXT=>"Полный текст новости",
PRESENT_DATE=>"Текущие новости",
FUTURE_DATE=>"Еще рано появляться",
PAST_DATE=>"Устаревшие",
EDIT_GROUPS_TEXT=>"Внизу окно управления новостями. Нажмите на (+), чтобы раскрыть группы. Чтобы добавить новую группу нажмите правой клавишей на названии групп и выберите 'Добавить страницу'. ",

TNEWSEVENT_ABOUT=>"Элемент загружающий и отображающий новость",

TNEWSEVENT_P_CSS_TITLE=>"Стиль заголовка",
TNEWSEVENT_P_CSS_DATE=>"Стиль текста даты",
TNEWSEVENT_P_CSS_AUTHOR=>"Стиль отображения имени автора",
TNEWSEVENT_P_CSS_INTRO=>"Стиль анонса",
TNEWSEVENT_P_SHOWDATE=>"Отображать дату",
TNEWSEVENT_P_HIDEALLTEXT=>"Не отображать текстовое содержимое. Только загрузить",
TNEWSEVENT_P_HIDEIMAGE=>"Не показывать изображение",
TNEWSEVENT_P_HIDEAUTHOR=>"Не показывать автора",

TNEWSEVENT_D_THENEWSEVENT=>"Новость",
TNEWSEVENT_D_THENEWSGROUP=>"Группа новостей",
TNEWSEVENT_D_TITLE=>"Заголовок новости",
TNEWSEVENT_D_BODY=>"Полный текст новости",
TNEWSEVENT_D_INTRO=>"Анонс новости",
TNEWSEVENT_D_SUBJECT=>"Тема:",

TNEWSEVENT_PLACED_IN_LAYOUT=>"Здесь будет новость. Вы сможете увидеть содержимое этого элемента только при просмотре страниц этого стиля",
TNEWSEVENT_D_DATE=>"Дата события",
TNEWSEVENT_D_AUTHOR=>"Автор текста",
TNEWSEVENT_D_DATETOSHOW=>"Когда показать новость",
TNEWSEVENT_D_DATETOHIDE=>"Когда убрать из списка",
NEWSBROWSER_P_NEWSGROUP=>"Выводить новости только указанной группы",
NEWS_TN_FORMAT=>"Формат миниатюры",

NEWS_PHOTO=>"Фото новости",
MONTHS_AGO=>"мес.назад",
ADD_NEW_EVENT=>"Добавить новую запись",
EVENT_WITHOUT_TITLE=>"(без заголовка)",
EVENT_WITHOUT_INTRO=>"Новость без анонса. При просмотре списков новостей не будет видно о чем эта новость",
WILL_BE_HREF_TO=>"Вместо новости открыть другой http адрес:",
ATTACH_FILE=>"Присоединить файл",
INTRO=>"Краткий анонс",
TITLE=>"Заголовок",
REMOVE_PHOTO=>"Удалить фото",
REMOVE_ATTACHMENT=>"Удалить файл",
ONLY_JPEG_ACCEPTED=>"(Укажите JPG-файл)",
BODY=>"Полный текст новости",
AUTHOR=>"Автор/источник",
AUTHOR_HTTP=>"WEB-сайт источника",
SAMPLE_NEWS_INTRO=>"Это пример текста новости, который может быть опубликован в каком-либо элементе страницы.
Новость может содержать большой объем текста, намного большим чем этот",
SAMPLE_NEWS_TITLE=>"Пример заголовка новости",
NO_NEWS_EVENTS=>"Новостных событий нет",
EVENTS_OF_A_DATE=>"Новостные события за ",
ALL_DATES_EVENTS=>"События за все даты",
NEWSDATEFORMAT=>"Формат отображения даты",
KEYWORDS=>"Ключевые слова",

PUBSTATUS=>"Состояние публикации",
PUBSTATUS_0=>"К просмотру",
PUBSTATUS_5=>"Требуется доработка",
PUBSTATUS_10=>"Опубликовано",


NEWSGROUP_CAPTION=>"Название текущей группы новостей",
NEWSGROUP_SUPERCAPTION=>"Название старшей группы новостей",
NEWSGROUP_TARGET_NEWSEVENTS_CONTEXT=>"Виртуальный раздел сайта, который выводит новости",

NEWSBROWSER_C_MORE=>"еще новости...",
NEWSBROWSER_C_DETAILS=>"подробнее..",
NEWSBROWSER_C_PAGES=>"страницы: ",
NEWSBROWSER_P_INTROLENGTH=>"Максимальная длина анонса (симв)",
NEWSBROWSER_P_EVENTSPERPAGE=>"Количество новостей на страницу",
NEWSBROWSER_BIND_TO_THIS_PAGE=>"Отображать новость текущей страницы",
NEWSBROWSER_GROUP_NAME_SAMPLE=>"Название текущей группы новостей",
NEWSBROWSER_SAMPLELIST=>"Здесь будут выведены заголовки новостей",
NEWSBROWSER_P_SHOWBODYASHREF=>"Краткое описание новости будет работать вместо ссылки 'подробнее'",
NEWSBROWSER_P_GROUPFROMEVENT=>"Укажите элемент, публикующий новость или группу новостей",
NEWSBROWSER_SHOWONERANDOM=>"Показывать одну произвольную новость",
NEWSBROWSER_CHECKFORDETAILS=>"Проверять наличие текста новости и убирать ссылку подробнее, если нет текста. Эта проверка добавляет еще один запрос к базе",
NEWSBROWSER_PAGES=>"Страницы новостей",

MOVE_NEWS_TO=>"Переместить в ",
TNEWSPATH_ABOUT=>"Печатает путь к загружаемой новости в виде ссылок на вышестоящие группы новостей",
TNEWSPATH_ATTACHROOT=>"Пристыковать другую ветку сайта",

TLASTEVENT_ABOUT=>"Последняя новость в списке",


TNEWSBROWSER_CAPTION=>'Список новостных заголовков',
TNEWSBROWSER_DESCRIPTION=>'Заголовок, вводная часть новости, и иконка со ссылкой на сам текст новости',
TNEWSEVENT_CAPTION=>'Публикатор новости',
TNEWSEVENT_DESCRIPTION=>'Загружает и публикует элементы новости на странице. Номер новости берется из номера открываемой страницы',
SETTING_MONTHSTOSHOW=>'Сколько месяцев отображать в списке новостей',
NEWSLIST_VIEW=>"Показать новости списком",
WEBSITE_VIEW=>"Как выглядит на сайте",

);
?>
