<?
$GLOBALS['_STRINGS']['store']=array(

STORE_CARTIDGE_TITLE =>"Торговая площадка",

ROLE_PRICE_UPLOADER  =>"Обновление прайса",
ROLE_DESCRIPTIONER   =>"Модификация описания товаров",
ROLE_REQUESTVIEW     =>"Просмотр заказов",
ROLE_REQUESTEDIT     =>"Редактирование заказов",

PACKAGE_WEIGHT=>"Вес упаковки",
PACKAGE_SIZE=>"Размер упаковки",
WEIGHT_LBS=>"фунт",
WEIGHT_OZ=>"унция",
WEIGHT_KGS=>"кг",
WEIGHT_G=>"грамм",
LENGTH_M=>"м",
LENGTH_CM=>"см",
LENGTH_FT=>"фут",
LENGTH_INCH=>"дюйм",
WIDTH=>"Ширина",
HEIGHT=>"Высота",
LENGTH=>"Длина",
WIDTH_LENGTH_NOTICE=>"Ширина - меньший горизонтальный размер, длина - больший",
USE_MEASUREMENT_SYSTEM_SI=>"Использовать систему измерения СИ для хранения и отображения веса и длин",
SETTINGS_ASK_PACKAGEWS=>"Редактор товаров будет запрашивать вес и габариты товара",


CAPTION_PRODUCTSCATALOGUE=>"Каталог товаров",
SELECT_EMPTY_IMAGE=>"Выберите изображение, которое будет показано вместо пустого",

TPRICELIST_P_TABLESTYLE=>"Стиль таблицы для вывода прайса",
TPRICELIST_BTN_PUTTOCART=>"Положить в корзину",
TPRICELIST_NOPRODUCTSINGROUP=>"Список товаров пуст",
TPRICELIST_SAMPLE=>"Здесь будет выводиться список товаров относительно выбранной группы товаров",
TPRICELIST_PRODUCTTARGETCONTEXT=>"Виртуальный раздел сайта, который будет показывать информацию о товаре",
TPRICELIST_JUMPAFTERPUT=>"На какую страницу перейти после того как посетитель положит товар в корзину",

TPRICEATTRSELECTOR=>"Выбор отображаемых параметров товара в прайс-листе",
TPRICEATTRSELECTOR_BUTTON=>"Показать характеристики",
TPRICEATTRSELECTOR_TITLE=>"Здесь Вы можете отобрать дополнительные характеристики, которые будут показаны в прайс-листе",
TPRICEATTRSELECTOR_TITLE_CSS=>"Стиль заголовочной надписи",
TPRICEATTRSELECTOR_OPTIONS_CSS=>"Стиль опций",
TPRICELIST_SHOW_VC_COLUMN=>"Показывать колонку с валютной ценой",
DATADEF_HIGHLIGHTED_OPTIONS=>"Выбранные опции",
DATADEF_DETECTED_OPTIONS=>"Список опций в текущей группе",

ISHOPCART=>"Товарная корзина",
ISHOPCART_ABOUT=>"Интерфейс для работы с товарной корзиной",
ISHOPCART_ERRORREQUESTID=>"Такая корзина не существует",
ISHOPCART_ERRORACCESS=>"Это не ваш запрос и вы не являетесь администратором",
ISHOPCART_NOSTATESDEFINED=>"Не указаны типы состояний заказов",

TSHOPCART_TEXTEMPTY=>"Ваша корзина пуста",
TSHOPCART_REQUESTSETS=>"Наборы товаров в составе запроса",
TSHOPCART_CAPTION_SET_TOTAL=>"Итого, стоимость конфигурации",
COLUMN_VCPRICE=>"Цена в у.е.",
COLUMN_BCPRICE=>"Цена",
COLUMN_GUARANTEE=>"Гарантия",
COLUMN_PRODUCTNAME=>"Название",
COLUMN_TOTAL=>"Всего",
COLUMN_ITEMCOUNT=>"Кол-во",
COLUMN_SETCOUNT=>"Кол-во комплектов",
BUTTON_UPDATESHOPCAR=>"Пересчитать",
WARNING_NOCURRENCIESDATA=>"Таблица валют не содержит информации ни об основной единице исчисления, ни о дополнительных!",
DEFAULT_SET_NAME=>"Конфигурация №",
DEFAULT_REQUEST_NAME=>"Заказ от ",

PRODUCTS_ADDNEW=>"Добавить товар",
PRODUCTS_GROUPNAME=>"Краткое название товарной группы",
PRODUCTS_GROUPTITLE=>"Заголовок товарной группы",
PRODUCT_NAME=>"Название товара",
PRODUCT_SKU=>"Артикул",
PRODUCT_MAINDATA=>"Основные параметры",
PRODUCT_PRICECOLUMNS=>"Колонки прайса",
PRODUCT_PRICES=>"Цены",
PRODUCT_DESCRIPTIONS=>"Описания товара",
PRODUCT_SUBPRODUCTS=>"Подтовары",
PRODUCT_IMAGE=>"Основное изображение товара",
PRODUCT_ATTRIBUTES=>"Характеристики",
PRODUCT_NEWDESCRIPTION=>"Введите заголовок нового описания",
PRODUCT_PUTHEREATTRIBUTES=>"Введите параметры товара и их значения в нижние поля",
PRODUCT_PHOTOALBUM=>"Фотоальбом о продукте",
PRODUCT_TEASER=>"Краткое привлекательное описание продукта (тизер)",
PRODUCT_HOTNEWSALE=>"Обычный,Суперпредложение!,Новинка!,Распродажа!,Нет на складе",
PRODUCT_HIDDEN=>"Убрать товар из списков",
PRODUCT_MORE=>"подробнее...",
PRODUCT_TEASERASLINK=>"Использовать текст о продукте как ссылку",
STORE_PRODUCT_OPTIONS=>"Опции товаров",
OPTION_NAME=>"Характеристика",
OPTION_UNIT=>"Ед.измерения",
OPTION_INFO=>"Доп.информация",
OPTION_VALUE=>"Значение",
OPTION_HIDDEN=>"Скрытая",
OPTION_VALUESCOUNT=>"Принимаемые значения (кол-во)",
OPTION_COLOUR=>"Цвет подсветки",
OPTION_HASIMAGE=>"Может иметь изображение",
OPTION_HASDESCRIPTION=>"Может иметь текстовое описание",
OPTION_HASURL=>"Может иметь ссылку URL",


TEXT_OPTION_VALUES=>"Значения, которые может принимать опция. Например: возможные цвета, размеры, диаметры и т.д.",
OPTION_USAGECOUNT=>"Кол-во товаров с этой опцией",
OPTION_ISPRODUCTSELECTBOX=>"Используется как падающий список выбора подтовара",
ADD_OPTION=>"Добавление характеристики",
ADD_ONE_OR_MORE_OPTION=>"Добавить одну или несколько характеристик",
ADD_NEW_OPTION=>"Добавить новую опцию",
ADD_OPTION_VALUES=>"Добавить значения атрибута",
SELECT_ONE_OR_MORE_OPTIONS_TO_ADD=>"Выберите один или несколько известных атрибутов для добавления",
REMOVING_UNUSABLE_VALUES=>"Удаление неиспользуемых значений опций",
REMOVE_VALUES_AND_SET_OPTION=>"Удалить выделенные значения и заменить их у товаров на другое : ",
JUST_REMOVE_VALUES=>"Удалить без замены",
PRODUCTS_OF_VALUE=>"Товары, которые имеют это значение опции",
SELECTED_SAME_VALUE_LIKE_REMOVING=>"Вы выбрали то же значение, что и исходное значение. Выберите другие исходные значения либо другое назначаемое значение",
ORDERNO=>"Порядок вывода на экран",
ADD_SUBPRODUCT=>"Добавление подтовара с другими значениями опций (размер/цвет и пр.)",
HINT_ADD_SUBPRODUCT=>"Вы можете оставить префикс '+' чтобы это название добавлялось к артикулу (SKU) через дефис и к имени базового товара через пробел",
EJECT_TO_PRODUCT=>"Выделить как товар",
CAPTION_RESORTPRODUCTS=>"Пересортировать товары",
MOVE_TO=>"Переместить в",


CSS_PRODUCT_NAME=>"Стиль текста названия товара",
CSS_PRODUCT_PRICE=>"Стиль текста цены товара",
CSS_PRODUCT_OTHER_PRICE=>"Стиль дополнительных цен",
CSS_PRODUCT_LINK=>"Стиль ссылки на подробности о товаре",
CSS_IMG_BORDER=>"Стиль обрамления изображений",

TITLE_STORE_SETTINGS=>"Установки интернет-магазина",

TPRODUCT=>"Загружает информацию о продукте и публикует ее на странице",

TPRICEATTRSELECTOR_CAPTION=>'Pricelist option selector',
TPRICEATTRSELECTOR_DESCRIPTION=>'Works within TPriceList that prints only products equal to this selector',
TPRICELIST_CAPTION=>'Pricelist for current group',
TPRICELIST_DESCRIPTION=>'Prints out pricelist table with current page ID. This control should be installed on the page of the product group',
TPRODUCT_CAPTION=>'The Product info',
TPRODUCT_DESCRIPTION=>'Loads product info (put this to a product layout)',
TPRODUCTSPAGE_CAPTION=>'The Products page',
TPRODUCTSPAGE_DESCRIPTION=>'Prints products of corresponding group within images in columns. (put this to a product group layout)',
TSHOPCART_CAPTION=>'User shopcart',
TSHOPCART_DESCRIPTION=>'Shows shopping cart content',

CURRENT_LANGUAGE=>"Текущий язык",
EDIT_CURRENCIES=>"Редактор валют",
EDIT_CURRENCY=>"Редактирование валюты",
ADD_CURRENCY=>"Регистрация новой валюты",
CURRENCY_NAME=>"Краткое название",
CURRENCY_NAME_NOTICE=>"3-символьное обозначение",
CURRENCY_CAPTION=>"Полное название",
CURRENCY_PREFIX=>"Префикс значений",
CURRENCY_SUFFIX=>"Суффикс значений",
CURRENCY_DECIMALS=>"Кол-во цифр после запятой",
CURRENCY_DECPOINT=>"Символ разделителя дроб. части",
CURRENCY_THOUSANDSSEP=>"Разделитель тысяч",

EDIT_PRICECOLUMNS=>"Редактор колонок прайса",
CATALOG_SECTION_IMAGE=>"Изображение текущего раздела каталога",
TCATALOGINDEX_CAPTION=>"Разделы каталога товаров",
TCATALOGINDEX_DESCRIPTION=>"Показывает разделы каталога соблюдая вложенность разделов одного в другой",

SETTINGS_GROUPCONTEXT=>"Контекст групп товаров",
SETTINGS_PRODUCTCONTEXT=>"Контекст товаров",
SETTINGS_OPTGRPCONTEXT=>"Контекст групп атрибутов товаров",
EDIT_CURRENCYRATES=>"Котировки валют",
);




?>
