<?
$GLOBALS['_STRINGS']['store']=array(
STORE_CARTIDGE_TITLE =>"Website store",

ROLE_PRICE_UPLOADER  =>"Price list updater",
ROLE_DESCRIPTIONER   =>"Products descriptions modification",
ROLE_REQUESTVIEW     =>"Orders viewing",
ROLE_REQUESTEDIT     =>"Orders editing",

PACKAGE_WEIGHT=>"Package weight",
PACKAGE_SIZE=>"Package size",
WEIGHT_LBS=>"lbs",
WEIGHT_OZ=>"oz",
WEIGHT_KGS=>"kgs",
WEIGHT_G=>"g",
WIDTH=>"Width",
HEIGHT=>"Height",
LENGTH=>"Length",
LENGTH_M=>"m",
LENGTH_CM=>"cm",
LENGTH_FT=>"ft",
LENGTH_INCH=>"in",
WIDTH_LENGTH_NOTICE=>"Measure the longest side of the package, rounding to the nearest inch. This is your length. Other side is width.",
USE_MEASUREMENT_SYSTEM_SI=>"Use measurement system SI to keep and output weight and size",
SETTINGS_ASK_PACKAGEWS=>"Product editor ask for package weight and size",

CAPTION_PRODUCTSCATALOGUE=>"Webstore products",
TPRICELIST_P_TABLESTYLE=>"Price list displaying table style",
TPRICELIST_NOPRODUCTSINGROUP=>"Product list is empty",
TPRICELIST_SAMPLE=>"The list of products for selected group will be displayed here",
TPRICELIST_PRODUCTTARGETCONTEXT=>"Virtual site section to display the information about product",
TPRICELIST_JUMPAFTERPUT=>"Page to go to after user puts a product to his basket",
SELECT_EMPTY_IMAGE=>"�������� �����������, ������� ����� �������� ������ �������",

TPRICEATTRSELECTOR=>"Selection of the displayed product parameters in the price list",
TPRICEATTRSELECTOR_BUTTON=>"Show characterisctics",
TPRICEATTRSELECTOR_TITLE=>"Here you can select additional characteristics to be shown in the price list",
TPRICEATTRSELECTOR_TITLE_CSS=>"Title text style",
TPRICEATTRSELECTOR_OPTIONS_CSS=>"Options style",
TPRICELIST_SHOW_VC_COLUMN=>"Show the currency price column",
DATADEF_HIGHLIGHTED_OPTIONS=>"Set of product parameters",
DATADEF_DETECTED_OPTIONS=>"Options that used in this product group",

ISHOPCART=>"Shopping cart",
ISHOPCART_ABOUT=>"Interface for work with the shopping cart",
ISHOPCART_ERRORREQUESTID=>"Such cart does not exist",
ISHOPCART_ERRORACCESS=>"This is not your request. You are not the system administrator",
ISHOPCART_NOSTATESDEFINED=>"Order status types are not defined",

TSHOPCART_TEXTEMPTY=>"You cart is empty",
TSHOPCART_REQUESTSETS=>"Product selections in the request",
TSHOPCART_CAPTION_SET_TOTAL=>"Total",
COLUMN_VCPRICE=>"Secondary value price",
COLUMN_BCPRICE=>"Price",
COLUMN_GUARANTEE=>"Guarantee",
COLUMN_PRODUCTNAME=>"Name",
COLUMN_TOTAL=>"Total",
COLUMN_ITEMCOUNT=>"Count",
COLUMN_SETCOUNT=>"Amount of sets",
BUTTON_UPDATESHOPCAR=>"Recalculate",
WARNING_NOCURRENCIESDATA=>"Currency table does not contain information about neither about the main currecy unit nor about additional ones!",
DEFAULT_SET_NAME=>"Configuration #",
DEFAULT_REQUEST_NAME=>"Order of  ",

PRODUCTS_ADDNEW=>"Add new product",
PRODUCTS_GROUPNAME=>"Product group name",
PRODUCTS_GROUPTITLE=>"Product group title",
PRODUCT_NAME=>"Product name",
PRODUCT_SKU=>"SKU",
PRODUCT_PRICECOLUMNS=>"Product price columns",
PRODUCT_PRICES=>"Prices",
PRODUCT_SUBPRODUCTS=>"Subproducts",
PRODUCT_DESCRIPTIONS=>"Product descriptions",
PRODUCT_IMAGE=>"Main product image",
PRODUCT_MAINDATA=>"Main parameters",
PRODUCT_ATTRIBUTES=>"Attributes",
PRODUCT_NEWDESCRIPTION=>"Enter title of new description",
PRODUCT_PUTHEREATTRIBUTES=>"Put product parameters in the text fields below",
PRODUCT_PHOTOALBUM=>"Product photo album",
PRODUCT_TEASER=>"Product teaser",
PRODUCT_HOTNEWSALE=>"Ordinal,Hot,New,Sale,Out of stock",
PRODUCT_HIDDEN=>"Exclude from lists",
PRODUCT_MORE=>"more..",
PRODUCT_TEASERASLINK=>"Use teaser text as link to product",
STORE_PRODUCT_OPTIONS=>"Product options",
OPTION_NAME=>"Attribute name",
OPTION_UNIT=>"Unit",
OPTION_INFO=>"Additional info",
OPTION_VALUE=>"Value",
OPTION_USAGECOUNT=>"Usage count of the options",
OPTION_ISPRODUCTSELECTBOX=>"Used as select box in products",
OPTION_HIDDEN=>"Hidden from users",
OPTION_VALUESCOUNT=>"Option values usage",
OPTION_COLOUR=>"Option highlight color",
OPTION_HASIMAGE=>"Has image",
OPTION_HASDESCRIPTION=>"Has text description",
OPTION_HASURL=>"Has URL reference",

TEXT_OPTION_VALUES=>"Option possible values. In example colours, sizes, diameters, watts e.t.c.",
ADD_OPTION=>"Add new option to product",
ADD_ONE_OR_MORE_OPTION=>"Add one or more attributes",
ADD_OPTION_VALUES=>"Add attribute values",
ADD_NEW_OPTION=>"Add new attribute",
REMOVING_UNUSABLE_VALUES=>"Removing of unusable values",
REMOVE_VALUES_AND_SET_OPTION=>"Remove selected values and set product values to",
JUST_REMOVE_VALUES=>"Just remove without changes",
PRODUCTS_OF_VALUE=>"These are products has this option value",
SELECTED_SAME_VALUE_LIKE_REMOVING=>"You have selected the same value as one of original values. Please select other source or other target",
ORDERNO=>"Order numbers of output",
ADD_SUBPRODUCT=>"Add sub product with differ options",
HINT_ADD_SUBPRODUCT=>"You may leave prefix '+' to make system add this values to the SKU or to the Name of BaseProduct.",
EJECT_TO_PRODUCT=>"Eject to product",
CAPTION_RESORTPRODUCTS=>"Resort products",
MOVE_TO=>"Move to",

CSS_PRODUCT_NAME=>"Style of the product name",
CSS_PRODUCT_PRICE=>"Style of the base currency product price",
CSS_PRODUCT_OTHER_PRICE=>"Style of the additional prices",
CSS_PRODUCT_LINK=>"Style of the link to product details",
CSS_IMG_BORDER=>"Thumbnail border style",

TITLE_STORE_SETTINGS=>"Webstore settings",
TPRODUCT=>"Loads info about product and publish it to the page",

TPRICEATTRSELECTOR_CAPTION=>'Pricelist option selector',
TPRICEATTRSELECTOR_DESCRIPTION=>'Works within TPriceList that prints only products equal to this selector',
TPRICELIST_CAPTION=>'Pricelist for current group',
TPRICELIST_DESCRIPTION=>'Prints out pricelist table with current page ID. This control should be installed on the page of the product group',
TPRODUCT_CAPTION=>'The Product info',
TPRODUCT_DESCRIPTION=>'Loads product info (put this to a product layout)',
TPRODUCTSPAGE_CAPTION=>'The Products page',
TPRODUCTSPAGE_DESCRIPTION=>'Prints products of corresponding group within images in columns. (put this to a product group layout)',
TSHOPCART_CAPTION=>'User shopcart',
TSHOPCART_DESCRIPTION=>'Shows shopping cart content',

CURRENT_LANGUAGE=>"Current language",
EDIT_CURRENCIES=>"Edit currencies",
EDIT_CURRENCY=>"Edit currency",
ADD_CURRENCY=>"Add currency",
CURRENCY_NAME=>"Currency short name",
CURRENCY_NAME_NOTICE=>"3-char symbolic name (i.e. USD,EUR)",
CURRENCY_CAPTION=>"Currency full name",
CURRENCY_PREFIX=>"Prefix",
CURRENCY_SUFFIX=>"Suffix",
CURRENCY_DECIMALS=>"Decimals count",
CURRENCY_DECPOINT=>"Decimal point symbol",
CURRENCY_THOUSANDSSEP=>"Thousands separator",

EDIT_PRICECOLUMNS=>"Edit price columns",
CATALOG_SECTION_IMAGE=>"Catalog section image",

TCATALOGINDEX_CAPTION=>"Catalog index",
TCATALOGINDEX_DESCRIPTION=>"Displays structured product catalog sections depend on tree structure",

SETTINGS_GROUPCONTEXT=>"Product group context",
SETTINGS_PRODUCTCONTEXT=>"Products context",
SETTINGS_OPTGRPCONTEXT=>"Product attributes groups context",
EDIT_CURRENCYRATES=>"Edit currency rates",
);




?>
