<?

$GLOBALS['_STRINGS']['jsb']=array(
TITLE=>"Website management",
TITLE_SITE_EDITOR=>"Site editor",
WIDTH=>"width",
HEIGHT=>"height",

ROLE_MAINDESIGNER=>"Main site designer",
ROLE_COMPOSER=>"Web site pages composer",

TITLE_THESE_ARE_LAYOUTS=>"Pages layouts",
TITLE_THESE_ARE_TEMPLATES=>"Available php templates",
PREVIEW_TEMPLATE=>"Preview template structure",
TITLE_THESE_ARE_CONTEXTS=>"Website contexts",
CAPTION_CONTEXTS=>"Site sections",
CAPTION_BROWSER_VIEWMODE=>"Viewing mode",
CAPTION_ADD_CONTEXT=>"Add new context",
MSG_CONTEXTS_UPDATED=>"Site context updated",
SELECT_THIS_CONTEXT=>"Select this context",

CONTEXT_IDENTIFIER=>"Context shortname (not more than 20 latin characters)",
CONTEXT_CAPTION=>"Full context title",
CONTEXT_LAYOUT=>"Layout used by default",
CONTEXT_OBJECTCLASS=>"Class of objects inside the section",
LAYOUT_OBJECTCLASS=>"Object class loads to the pages of this layout",
CONTEXT_HAS_NO_LAYOUT=>"Context has no layout",
MISSING_LAYOUT=>"Missing layout. Possibly layout has been removed",

CAPTION_UNKNOWN_UP_DATE=>"---",
MSG_CONTEXT_HAS_NO_PAGES=>"No pages in this section",
ERROR_DOCNOTFOUND=>"Page not found",
ERROR_EMPTYCAPTION=>"Page caption cannot be blank",
ERROR_BAD_CONTROLID=>"Incorrect element number",
ERROR_CONTROL_NOTFOUND=>"Element file not found",
ERROR_NO_THEME_FILE=>"File of theme.php not found",

MSG_PLEASE_SELECT_PAGE_IN_TREE=>"Select a page for viewing in the left panel",
MSG_ERROR_IN=>"Error in",
CAPTION_PAGE_PROPERTIES=>"Page properties",
CAPTION_PAGE_MENUCAPTION=>"Menu item caption",
CAPTION_PAGE_TITLE=>"Page title",
CAPTION_PAGE_LAYOUT=>"Page layout",
CAPTION_PAGE_KEYWORDS=>"Keywords",
CAPTION_PAGE_DESCRIPTION=>"Page description",
CAPTION_PAGE_DATE=>"Modification date",
CAPTION_MODIFY=>"Modify",
CAPTION_LAYOUT=>"Layout",
CAPTION_LITERAL=>"Symbol",
CAPTION_DATE=>"Date",
CAPTION_TEMPLATE=>"PHP Template",
CAPTION_REMOVETO=>"Remove and replace with",
ERROR_REPLACE_TO_DEADSTYLE=>"Cannot replace the page layout with being removed one. Select another layout, to recomplile the elemets of all its pages.",

CAPTION_SETHOMEPAGE=>"Set page to home",
CAPTION_ATTACH_PAGE=>"Attach other menu section",
CAPTION_VIRTUAL_PAGE=>"Display other page instead",
CAPTION_SAVE=>"Save",
CAPTION_NONAME=>"No name",
CAPTION_VIEWMODE=>"View",
CAPTION_VIEWCOUNT=>"View count",
CAPTION_RENAME_PAGE=>"Rename",
CAPTION_INSERT_PAGE_BEFORE=>"Add page before this",
CAPTION_INSERT_PAGE_AFTER=>"Add page",
CAPTION_INSERT_PAGE_INSIDE=>"Insert new page",
CAPTION_CHANGELAYOUT=>"Change page layout",
CAPTION_SHOWHIDDEN=>"Show recycled pages",
CAPTION_HIDEHIDDEN=>"Do not show recycled",
CAPTION_HIDE=>"Hide selected",
CAPTION_UNHIDE=>"Unhide selected",
CAPTION_RECYCLE=>"Put to recycle bin",
CAPTION_PUTBEFORE=>"Put before",
CAPTION_PUTAFTER=>"Put after",
CAPTION_PUTINSIDE=>"Put inside",
CAPTION_DUPLICATE=>"Duplicate page",
CAPTION_CHANGE_LAYOUT_TO=>"Change layout to:",
CAPTION_DETACH_PAGE=>"Detach menu",
CAPTION_DEVIRT_PAGE=>"Cancel page substitution",
MSG_NO_SELECTED_PAGES=>"Select one or more pages before opearing in 'Modify' menu'",
TITLE_SELECT_PAGE=>"Select page�",
MSG_SELECT_A_PAGE=>"Please select a page in the left panel and click it",
CAPTION_RequiredProperty=>"(required)",
TITLE_SELECT_PHTMLTEMPLATE=>"Select basic template for this layout",

CAPTION_REFRESH=>"Refresh",
CAPTION_EDIT_CONTEXTS=>"Site sections",
CAPTION_EDIT_LAYOUTS=>"Pages layouts",
CAPTION_LAYOUT_NAME=>"Layout name",
CAPTION_ADD_LAYOUT=>"Add a new page layout",
CAPTION_BINDTO_CURRENTPAGE=>"Bind to current page",
MSG_BINDTO_OBJECT=>"Binding is doen to  %s object",
CAPTION_REGENERATE=>"Regenerate",
CAPTION_EDIT=>"Edit",

CAPTION_ADD_CONTROL=>"Add a new element",
CAPTION_CARTRIDGE_INACTIVE=>"Elements of this cartridge are deactivated. Please contact the site admin for activation",
CAPTION_NO_REFERENCE=>"(no reference)",
CAPTION_ADD_THIS_CONTROL=>"Add",

TPAGE_THEPAGE=>"Current webpage",
TPAGE_PAGECAPTION=>"Short page name",
TPAGE_PAGETITLE=>"Page title",
TPAGE_PARENTTITLE=>"Full section title",
TPAGE_PARENTCAPTION=>"Short section title",
TPAGE_TOP_TITLE=>"Main section title",
TPAGE_PATHBAR=>"Path to the page with links to sections",
TLAYOUT_CAPTION=>"Page layout name",
ACTIVATE_THIS_THEME=>"Set this theme as main",
TMENU_EMPTY_MENU=>"Empty menu",
CAPTION_EDIT_THEMES=>"Changing main theme",
THEME_TEMPLATES=>"Templates availalbe for use",
TITLE_EDIT_THEME=>"Site theme selection",
THEME_CHANGED=>"Site theme activated",
THEME_NO_TEMPLATES=>"Theme has no templates",
MAIN_THEME=>"Main site theme",
CHOOSE_CARTRIDGE_AT_LEFT=>"Select the cartridge on the left and then add a control by simple clicking on it",


MSG_ENTER_URL=>"Enter the full URL address of the page the link will point to",
MSG_SELECT_SITEPAGE=>"You can select one of the site pages the link will point to",
CAPTION_OPENCONTEXT=>"Open this section",
SELECT_CONTEXT=>"Select section",
ICONTEXT_REMOVE_CONFIRMATION=>"Are you sure you want to delete these sections, and all pages inside them?",
ICONTEXT_REMOVE_COMPLETE=>"The selected section were removed. To remove the physsical objects run the garbage removal utility",
ICLEAN_TITLE=>"Erase pages from recycle bin",
ICLEAN_CONFIRM=>"Are you sure you want to delete the following pages",
ICLEAN_COMPLETE=>"Pages and their elements from the following list are removed",
IPAGEINFOEDITOR=>"Page info editor",
CAPTION_ENVIRONMENTMODE=>"Environment design mode",
CAPTION_SETADMINACTION=>"Set action to admin menu item",

TEXT_THISISADMINMENU=>"This is the administration  menu section. You can add and edit the menu items, assigning to each an executable action.",
HOMEPAGE_LOCALURL=>"Homepage localurl (i.e.:'en/site/304')",

CLEAR_TMP=>"Clear temporary files",
CAPTION_EDITADMINMENU=>"Customize top menu",
CAPTION_PAGEDESIGN=>"Page design",
ROOT_PAGE_FOR_CONTEXT=>"Context root",
CHOOSE_TABLE_STYLE=>"Choose table style",
HOME_CONTEXT=>"Home context",
SETTING_DISABLECACHE=>"Disable page caching",
SETTING_SHOWCONTROLICONS=>"Show page control icons in the page editor",
);
?>
