<?
$GLOBALS['_STRINGS']['jsb']=array(
TITLE=>"Построитель сайта",
TITLE_SITE_EDITOR=>"Редактор сайта",
WIDTH=>"ширина",
HEIGHT=>"высота",

ROLE_MAINDESIGNER=>"Главный дизайнер сайта",
ROLE_COMPOSER=>"Верстальщик страниц сайта",

TITLE_THESE_ARE_LAYOUTS=>"Макеты страниц",
TITLE_THESE_ARE_TEMPLATES=>"Доступные PHTML-шаблоны страниц",
TITLE_THESE_ARE_CONTEXTS=>"Разделы сайта (контексты)",
PREVIEW_TEMPLATE=>"Посмотреть структуру шаблона",
CAPTION_CONTEXTS=>"Разделы сайта",
CAPTION_BROWSER_VIEWMODE=>"Режим просмотра",
CAPTION_ADD_CONTEXT=>"Добавить новый раздел",
MSG_CONTEXTS_UPDATED=>"Разделы сайта обновлены",
SELECT_THIS_CONTEXT=>"Выбрать этот раздел",

CONTEXT_IDENTIFIER=>"Индентификатор раздела",
CONTEXT_IDENTIFIER_NOTICE=>"только латинские буквы и цифры без пробелов",
CONTEXT_CAPTION=>"Полное название раздела",
CONTEXT_LAYOUT=>"Макет используемый по-умолчанию",
CONTEXT_OBJECTCLASS=>"Класс объектов, которые находятся в разделе",
LAYOUT_OBJECTCLASS=>"Класс объекта, загружаемого в страницы этого макета",
CONTEXT_HAS_NO_LAYOUT=>"Для раздела не указан макет",
MISSING_LAYOUT=>"Используется ошибочный макет. Возможно он был удален ",

CAPTION_UNKNOWN_UP_DATE=>"---",
MSG_CONTEXT_HAS_NO_PAGES=>"В данном разделе нет страниц",
ERROR_DOCNOTFOUND=>"Страница не найдена",
ERROR_EMPTYCAPTION=>"Название страницы не может быть пустым",

ERROR_BAD_CONTROLID=>"Некорректный номер элемента",
ERROR_CONTROL_NOTFOUND=>"Не найден файл элемента",
ERROR_NO_THEME_FILE=>"Не найден файл темы theme.php",


MSG_PLEASE_SELECT_PAGE_IN_TREE=>"Выберите страницу для просмотра в левой панели",
MSG_ERROR_IN=>"Ошибка в",
CAPTION_PAGE_PROPERTIES=>"Свойства страницы",
CAPTION_PAGE_MENUCAPTION=>"Текст пункта меню",
CAPTION_PAGE_TITLE=>"Заголовок страницы",
CAPTION_PAGE_KEYWORDS=>"Ключевые слова",
CAPTION_PAGE_DESCRIPTION=>"Описание страницы",
CAPTION_PAGE_LAYOUT=>"Макет страницы",
CAPTION_PAGE_DATE=>"Дата изменения",
CAPTION_MODIFY=>"Изменить",
CAPTION_LAYOUT=>"Макет",
CAPTION_LITERAL=>"Символ",
CAPTION_DATE=>"Дата",
CAPTION_TEMPLATE=>"Шаблон",
CAPTION_REMOVETO=>"Удалить, заменяя на",
ERROR_REPLACE_TO_DEADSTYLE=>"Не могу заменить макет страниц на удаляемый. Вам надо выбрать какой-то другой макет, в который будут перекомпанованы элементы всех его страницы.",

CAPTION_SETHOMEPAGE=>"Сделать страницу главной",
CAPTION_ATTACH_PAGE=>"Вложить меню другого раздела",
CAPTION_VIRTUAL_PAGE=>"Подстановка другой страницы",
CAPTION_SAVE=>"Сохранить",
CAPTION_NONAME=>"Без имени",
CAPTION_VIEWMODE=>"Вид",
CAPTION_VIEWCOUNT=>"Кол-во показов",
CAPTION_RENAME_PAGE=>"Переименовать",
CAPTION_INSERT_PAGE_BEFORE=>"Добавить страницу перед этой",
CAPTION_INSERT_PAGE_AFTER=>"Добавить страницу",
CAPTION_INSERT_PAGE_INSIDE=>"Вложить новую страницу",
CAPTION_CHANGELAYOUT=>"Сменить макет страницы",
CAPTION_SHOWHIDDEN=>"Показать удаленные страницы",
CAPTION_HIDEHIDDEN=>"Не показывать удаленные",
CAPTION_HIDE=>"Спрятать выбранные",
CAPTION_UNHIDE=>"Показать выбранные",
CAPTION_RECYCLE=>"Удалить выбранные в корзину",
CAPTION_PUTBEFORE=>"Положить перед",
CAPTION_PUTAFTER=>"Положить после",
CAPTION_PUTINSIDE=>"Вложить внутрь",
CAPTION_DUPLICATE=>"Дублировать страницу",
CAPTION_CHANGE_LAYOUT_TO=>"Изменить макет на:",
CAPTION_DETACH_PAGE=>"Отсоединить меню",
CAPTION_DEVIRT_PAGE=>"Отменить подстановку страницы",
MSG_NO_SELECTED_PAGES=>"Сначала выберите одну или более страниц, затем выполняйте действия в меню 'Изменить'",
TITLE_SELECT_PAGE=>"Выберите страницу",
MSG_SELECT_A_PAGE=>"Пожауйста выберите страницу в левой панели и нажмите на нее",
CAPTION_RequiredProperty=>"(обязательное)",
TITLE_SELECT_PHTMLTEMPLATE=>"Выберите базовый шаблон для этого макета",

CAPTION_REFRESH=>"Обновить",
CAPTION_EDIT_CONTEXTS=>"Разделы сайта",
CAPTION_EDIT_LAYOUTS=>"Макеты страниц",
CAPTION_LAYOUT_NAME=>"Название макета",
CAPTION_ADD_LAYOUT=>"Добавить новый макет страниц",
CAPTION_BINDTO_CURRENTPAGE=>"Привязать к тек. странице",
MSG_BINDTO_OBJECT=>"Привязка выполнена к объекту %s",
CAPTION_REGENERATE=>"Регенерировать",
CAPTION_EDIT=>"Редактировать",

CAPTION_ADD_CONTROL=>"Добавить новый элемент",
CAPTION_CARTRIDGE_INACTIVE=>"Элементы этого картриджа деактивизированы. Чтобы их активизировать необходимо связаться с администратором сайта",
CAPTION_NO_REFERENCE=>"(без привязки)",
CAPTION_ADD_THIS_CONTROL=>"Добавить",

TPAGE_THEPAGE=>"Текущая веб-страница",
TPAGE_PAGECAPTION=>"Краткое имя страницы",
TPAGE_PAGETITLE=>"Название страницы",
TPAGE_PARENTTITLE=>"Полное название раздела",
TPAGE_PARENTCAPTION=>"Краткое имя раздела",
TPAGE_TOP_TITLE=>"Название главного раздела",
TPAGE_PATHBAR=>"Путь к странице со ссылками на разделы",
TLAYOUT_CAPTION=>"Название макета страницы",
ACTIVATE_THIS_THEME=>"Сделать тему основной",
TMENU_EMPTY_MENU=>"Меню пустое",
CAPTION_EDIT_THEMES=>"Смена общей темы",
THEME_TEMPLATES=>"Темы, которые можно использовать",

TITLE_EDIT_THEME=>"Выбор темы сайта",
THEME_CHANGED=>"Новая тема сайта активизирована",
THEME_NO_TEMPLATES=>"Шаблонов нет",
MAIN_THEME=>"Основная тема сайта",
CHOOSE_CARTRIDGE_AT_LEFT=>"Выберите картридж слева и затем добавьте контрол, простым нажатием на его изображение",


MSG_ENTER_URL=>"Введите полный адрес URL той страницы, на которую будет указывать ссылка",
MSG_SELECT_SITEPAGE=>"Вы можете выбрать одну из страниц сайта, на которую будет указаны ссылка",
CAPTION_OPENCONTEXT=>"Открыть этот раздел",
SELECT_CONTEXT=>"Укажите раздел",
ICONTEXT_REMOVE_CONFIRMATION=>"Вы уверены, что хотите удалить эти разделы и все страницы, которые входят в них?",
ICONTEXT_REMOVE_COMPLETE=>"Указанные разделы были удалены. Чтобы удалить физические объекты необходимо задействовать утилиту очистки мусора",
ICLEAN_TITLE=>"Очистка от удаленных страниц",
ICLEAN_CONFIRM=>"Вы согласны, что хотите удалить следующие страницы",
ICLEAN_COMPLETE=>"Удалены страницы и их элементы следующего списка",
IPAGEINFOEDITOR=>"Редактор информации о странице",
CAPTION_CALLINTERFACEMETHOD=>"Запускаемый метод интерфейса",
CAPTION_ENVIRONMENTMODE=>"Дизайн страницы",
CAPTION_SETADMINACTION=>"Назначение действия на пункт меню",

TEXT_THISISADMINMENU=>"Это раздел административного меню. Вы можете добавлять и редактировать пункты меню, назначая каждому из них выполняемое действие.",
HOMEPAGE_LOCALURL=>"Адрес главной страницы (например: 'ru/site/304')",


CLEAR_TMP=>"Очистка временных файлов",
CAPTION_EDITADMINMENU=>"Настройка верхнего меню",
CAPTION_PAGEDESIGN=>"Страницы сайта",
ROOT_PAGE_FOR_CONTEXT=>"Корневая страница для раздела",
CHOOSE_TABLE_STYLE=>"Выберите стиль таблицы",
HOME_CONTEXT=>"Домашний раздел сайта",
SETTING_DISABLECACHE=>"Выключить кэширование страниц",
SETTING_SHOWCONTROLICONS=>"Показывать пиктограммы элементов страницы в редакторе",

);
?>
