<?
$GLOBALS['_STRINGS']['stdctrls']=array(
TITLE=>"Стандартные элементы страниц",
SITEPATH_ABOUT=>"Путь к странице сайта",
SITEPATH_ATTACHROOT=>"Пристыковать к ветке другого дерева сайта",

SITETEXT_ABOUT=>"Блок текста",
SITETEXT_BINDTOTEXT=>"Какая текстовая информация будет отображаться в этом блоке",
SITETEXT_P_CSSTEXT=>"Стиль текста",
SITETEXT_P_ALIGN=>"Выравнивание текста",
SITETEXT_V_ALIGNLEFT=>"Влево",
SITETEXT_V_ALIGNRIGHT=>"Вправо",
SITETEXT_V_ALIGNJUSTIFY=>"По ширине",
SITETEXT_V_ALIGNCENTER=>"По центру",
SITETEXT_V_EmptyBlock=>"Нажмите для ввода текста",
SITETEXT_TITLESAMPLE=>"Заголовок страницы",
SITETEXT_TEXT=>"Строка для отображения, если не указана привязка",
SITETEXT_TEXT_SAMPLE=>"Здесь будет отображаться динамическая информация, публикуемая другим элементом. ",
SITETEXT_CROPPING=>"Обрезать отрисовываемый текст по ширине",
RT_LAYOUT_SAMPLETEXT=>"<h3>Заготовка HTML-текста</h3>В страницах сайта, которые созданы на основе этого макета внутри этой заготовки можно будет ввести полноценный HTML-текст, содержащий графику, таблицы и разноформатный текст.",
TDRAWTEXT_RENDERASTEXT=>"Элемент TDrawText будет печатать все заголовки текстом, а не графикой",

TMENU_ABOUT=>"Падающее меню для навигации по сайту",
STYLE_LEFTMENU=>"Открывающееся меню слева",
STYLE_HEADMENU=>"Падающее меню справа-вверху",
STYLE_TOPMENU=>"Самое верхнее маленькое меню",
TMENU_STYLE=>"Стиль меню",
TMENU_ROOT=>"Раздел сайта или страница относительно которой будет строиться меню",
TMENU_EMBEDINPAGE=>"Внедрять структуру меню в страницу",


RICHTEXT_ABOUT=>"Форматированный текст",
RT_COPY=>"Копировать",
RT_CUT=>"Вырезать",
RT_PASTE=>"Вставить",
RT_INSERTCOL=>"Добавить колонку слева",
RT_INSERTROW=>"Добавить строку сверху",
RT_DELETECOL=>"Удалить колонку",
RT_DELETEROW=>"Удалить строку",
RT_INSERTROWBELOW=>"Добавить строку ниже",
RT_INSERTCOLRIGHT=>"Добавить колонку правее",
RT_INSERTORDEREDLIST=>"Нумерованный список",
RT_INSERTUNORDEREDLIST=>"Список",
RT_SELECT_TABLEAUTOFORMAT=>"Выбрать этот формат",
RT_BAD_BINDING=>"Неправильная стыковка объекта stdctrls.richtext",
RT_TABLESTYLE=>"Сменить стиль таблицы",
RT_CLEAR_TEXT_STYLE=>"Убрать формат",
RT_UNFORMATTED=>"(не форматирован)",
RT_LINK=>"Установить ссылку",
RT_IMAGE=>"Вставить изображение",
RT_IMAGE_PROPERTIES=>"Параметры изображения",
RT_TABLE=>"Вставить таблицу",
RT_REDO=>"Вернуть",
RT_UNDO=>"Отменить",
RT_BOLD=>"Жирный",
RT_ITALIC=>"Наклонный",
RT_UNLINK=>"Убрать ссылку",
RT_FILE_NOT_FOUND=>"Ошибка при чтении документа. Элемент необходимо удалить.",
RT_EDITCONTENT=>"Редактировать",
RT_CSS_DOCUMENTLINK=>"Стиль текста ссылок на смежные документы",
RT_CSS_DOCUMENTTITLE>"Стиль заголовка документа",
RT_SEPARATE_TO_PAGES=>"Смежные документы размещаются на отдельных страницах",
RT_NEW_PAGE_TITLE=>"Введите заголовок новой страницы",
RT_PAGE_TITLE=>"Название страницы",
RT_PAGE_NO=>"Порядковый номер страницы",
RT_PAGE_DEFAULT_TITLE=>"стр. ",
RT_DELETEPAGE=>"Удалить",
RT_ADD_PAGE=>"Добавить страницу",
RT_TEXTIFEMPTY=>"Текст, который будет выводиться, если контейнер пуст",
RT_SHIFTPAGERIGHT=>"Сдвинуть страницу вправо",
RT_SHIFTPAGELEFT=>"Сдвинуть страницу влево",


ADDDOC_SELECTFILE=>"Укажите файл, который будет помещен",
ADDDOC_SELECTICON=>"Файл-значок (ссылка будет нарисована с этой картинкой)",
RT_IMG_ALIGN_INLINE=>"Изображение перемещается в тексте",
RT_IMG_ALIGN_LEFT=>"Изображение выравнивать вправо",
RT_IMG_ALIGN_RIGHT=>"Изображение выравнивать влево",
RT_IMG_TITLEINSERT=>"Добавление изображения",
RT_IMG_SELECTFILE=>"Выберите файл изображения, который будет вложен. Это должен быть файл с расширением 'JPG'. Размер файла не должен превышать 2 Мбайт ",
RT_IMG_TOOLARGE=>"Слишком большое изображение. Соптимизируйте его и попробуйте еще раз. Размер файла не должен превышать 2 мегабайта",
RT_IMG_BADTYPE=>"Файл изобажения должен иметь формат JPG",
RT_IMG_RESETSIZE=>"Вернуть исходный размер изображения",
RT_DYNAMIC_BIND_SAMPLE=>"Здесь будет отображаться текст, относящийся к другому объекту",
RT_EDITABLE_BY_OWNER=>"Пользователь может редактировать, если является владельцем объекта, к которому присоединен этот текст",


TLINKLIST_ABOUT=>"Ссылки на страницы раздела",
LINKLIST_STYLE=>"Как вывести ссылки",
LINKLIST_STYLE_SIMPLE=>"В строчку: одну ссылку за другой",
LINKLIST_STYLE_HORIZONTAL=>"Горизонтально в таблице",
LINKLIST_STYLE_WIDELINE=>"Горизонтально во всю ширину",
LINKLIST_STYLE_VERTICAL=>"Вертикально",
LINKLIST_BEFORE=>"Текст перед ссылкой",
LINKLIST_AFTER=>"Текст после ссылки",
LINKLIST_BETWEEN=>"Текст между ссылками",
LINKLIST_P_CSSHREF=>"Стиль ссылок",
TLINKLIST_PADDING=>"Отступ внутри ячейки",

THTMLLIB_ABOUT =>"Отображает библиотеку HTML-заготовок, которые спроектированы дизайнером. Заготовки должны лежать в папке темы и иметь расширение '.lib.html'.
   Элементы заготовки разделяются
   ---BLOCKBEGIN назвблока---
     пользовательский HTML-код
   ---BLOCKEND---",
THTMLLIB_NOLIBFILEFOUND=>"Файл библиотеки не найден",
THTMLLIB_SELECT_ITEM=>"Выбрать элемент",
THTMLLIB_LIBNAME=>"Название файла библиотеки без расширения (не пишите .lib.html)",
TSOCKET_SOCKETADDRESS=>"Адрес сокета",

DRAWTEXT_FONTSTYLE=>"Стиль шрифта темы",
DRAWTEXT_ASTEXT=>"Печатать заголовок как текст, не рисовать",
BUTTON_RENDER_ASTEXT=>"Вместо картинки рисовать текстовую кнопку",
BUTTON_LINKTO=>"Адрес ссылки на документ сайта или в интернете для перехода при нажатии",

TPAGEBUTTONS_BINDTOCONTROL=>"Ссылка на многостраничный контрол",
TPAGEBUTTONS_STYLE=>"Стиль кнопок ссылок на страницы",
TPAGEBUTTONS_STYLE_SIMPLETEXT=>"Простые текстовые названия страниц",
TPAGEBUTTONS_STYLE_BUTTONS=>"В виде кнопок",
TPAGEBUTTONS_CAPTION_PAGES=>"страницы: ",
TPAGEBUTTONS_CAPTION_PAGEPREV=>"пред",
TPAGEBUTTONS_CAPTION_PAGENEXT=>"след",
TPAGEBUTTONS_CAPTION_PAGELAST=>"последняя",

TBUTTON_CAPTION=>"Кнопка",
TBUTTON_DESCRIPTION=>"Отображает кнопку, описанную в теме сайта",
TDRAWTEXT_CAPTION=>"Рисованный текст",
TDRAWTEXT_DESCRIPTION=>"Рисует текст в виде JPG, GIF или PNG изображения, используя шрифты и изображения, описанные в файле theme.php",
THTMLLIBRARY_CAPTION=>"Элемент HTML-библиотеки",
THTMLLIBRARY_DESCRIPTION=>"Prints out HTM snippet from website library Snippets whould be placed in the theme folder and has suffix '.lib.html'. Each library file has more than one snippet marked as ---BLOCKBEGIN and ---BLOCKEND words in the start of the line",
TJSMENU_CAPTION=>"Падающее меню",
TJSMENU_DESCRIPTION=>"Drop down menu on JAVASCRIPT. Menu generated only once per user and keeping in 'files' folder. If menu frequentially changed set the 'Embed in page' checkbox. This prevent from caching",
TLINKLIST_CAPTION=>"Ссылки на соседние страницы раздела",
TLINKLIST_DESCRIPTION=>"Отображает список ссылок на страницы указанного раздела или текущего по отношению к данной странице",
TPAGEBUTTONS_CAPTION=>"Кнопки выбора страниц",
TPAGEBUTTONS_DESCRIPTION=>"Отображает кнопки с номерами страниц или их названиями (TNewsBrowser,TProductsPage)",
TPATH_CAPTION=>"Путь к текущей странице",
TPATH_DESCRIPTION=>"Отображает путь от корня сайта до данной страницы. Можно не показывать корневую страницу или продолжить другое дерево",
TRICHTEXT_CAPTION=>"Текст HTML",
TRICHTEXT_DESCRIPTION=>"Отображает текстовый блок, присоединенный к объекту на странице или позволяет создать текст в привязке к данной странице сайта.",
TTEXT_CAPTION=>"Text label",
TTEXT_DESCRIPTION=>"Text label that prints out text published by other page control",

SETTING_RICHTEXTIMGLIMITS=>"When users upload an image in richtext editor the image will be resampled if greater that limit size",
SETTING_RICHTEXTIMAGESQUALITY=>"The quality of image file",
TVERTICALMENU_CAPTION=>"Hierarchical tree menu",
TVERTICALMENU_DESCRIPTION=>"Displays link to pages as vertical menu with subtree",

TCOLUMNS_CAPTION=>"Колонки",
TCOLUMNS_DESCRIPTION=>"Делит слот на колонки заданного стиля",
TCOLUMNS_STYLE=>"Стиль оформления (элементов темы 'ColumnStyles')",
TCOLUMNS_COUNT=>"Количество колонок",
TCOLUMNS_PADDING=>"Отступ внутрь колонок в пикселях",
TCOLUMNS_WIDTHS=>"Ширины колонок (точки или проценты) через запятую",
VERTICAL_SEPARATOR_STYLE=>"Стиль вертикального разделителя (для колонок без оформления)",
TCOLUMNS_HEADER_COLORS=>"Цвета заголовков колонок через запятую, например: green,#0000ff,red",
TCOLUMNS_COLUMN_COLORS=>"Цвета самих колонок через запятую, например: #f0ffff,#fffff8,#f8f8f8",
TCOLUMNS_SHOW_HEADER=>"Показывать заголовок колонки",

);

?>
