<?
$GLOBALS['_STRINGS']['stdctrls']=array(
TITLE=>"Standard controls",
SITEPATH_ABOUT=>"Path to the page (breadcrumb)",
SITEPATH_ATTACHROOT=>"Link other site branch to the path",

SITETEXT_ABOUT=>"Text block",
SITETEXT_BINDTOTEXT=>"Which Text should be printed in this block",
SITETEXT_P_CSSTEXT=>"CSS text style",
SITETEXT_P_ALIGN=>"Text alignment",
SITETEXT_V_ALIGNLEFT=>"Left",
SITETEXT_V_ALIGNRIGHT=>"Right",
SITETEXT_V_ALIGNJUSTIFY=>"To width",
SITETEXT_V_ALIGNCENTER=>"Center",
SITETEXT_V_EmptyBlock=>"Text block is empty. Click here to change it",
SITETEXT_TITLESAMPLE=>"[Page title]",
SITETEXT_TEXT=>"Text to print if no binding set",
SITETEXT_TEXT_SAMPLE=>"[Here will be printed text published by other control]",
SITETEXT_CROPPING=>"Crop drawable text by width boundary",
TDRAWTEXT_RENDERASTEXT=>"TDrawText will only print a text headers",

TMENU_ABOUT=>"Dropdown navigation menu",
STYLE_LEFTMENU=>"Left menu style",
STYLE_HEADMENU=>"Main menu style",
STYLE_TOPMENU=>"Topmost menu style",
TMENU_STYLE=>"Menu style",
TMENU_ROOT=>"Root site tree node",
TMENU_EMBEDINPAGE=>"Embed javascript menu data in page (used for small weight menu)",


RICHTEXT_ABOUT=>"Rich formatting text",
RT_LAYOUT_SAMPLETEXT=>"<h3>HTML-text sample</h3>In all pages of current layout you can change text in this block",
RT_COPY=>"Copy",
RT_CUT=>"Cut",
RT_PASTE=>"Paste",
RT_INSERTCOL=>"Insert column left",
RT_INSERTROW=>"Insert column above",
RT_DELETECOL=>"Remove column",
RT_DELETEROW=>"Remove row",
RT_INSERTROWBELOW=>"Insert row below",
RT_INSERTCOLRIGHT=>"Insert column right",
RT_INSERTORDEREDLIST=>"Numbered list",
RT_INSERTUNORDEREDLIST=>"Bulettin list",
RT_SELECT_TABLEAUTOFORMAT=>"Choose this table format",
RT_BAD_BINDING=>"[Bad binding stdctrls.richtext]",
RT_TABLESTYLE=>"Change table style",
RT_CLEAR_TEXT_STYLE=>"Clear formatting",
RT_UNFORMATTED=>"(non-formatted)",
RT_LINK=>"Set link",
RT_IMAGE=>"Insert image",
RT_IMAGE_PROPERTIES=>"Image properties",
RT_TABLE=>"Insert table",
RT_REDO=>"Redo",
RT_UNDO=>"Undo",
RT_BOLD=>"Bold",
RT_ITALIC=>"Italic",
RT_UNLINK=>"Remove link",
RT_FILE_NOT_FOUND=>"Error readng file. This element should be removed.",
RT_EDITCONTENT=>"Edit content",
RT_CSS_DOCUMENTLINK=>"Style of the link to other documents in the set",
RT_CSS_DOCUMENTTITLE>"Style of the document title",
RT_SEPARATE_TO_PAGES=>"This control prints text documents into separate pages",
RT_NEW_PAGE_TITLE=>"Enter the title of the new text page",
RT_PAGE_TITLE=>"Title of the text page",
RT_PAGE_NO=>"Page output order number",
RT_PAGE_DEFAULT_TITLE=>"page #",
RT_ADD_PAGE=>"Add page",
RT_DELETEPAGE=>"Delete page",
RT_TEXTIFEMPTY=>"Text to output if bind container is empty",
RT_SHIFTPAGERIGHT=>"Shift page to right",
RT_SHIFTPAGELEFT=>"Shift page to left",


ADDDOC_SELECTFILE=>"Choose file to be inserted",
ADDDOC_SELECTICON=>"Choose icon-file for this file",
RT_IMG_ALIGN_INLINE=>"Image has no alignment",
RT_IMG_ALIGN_LEFT=>"Image aligned to the left",
RT_IMG_ALIGN_RIGHT=>"Image aligned to the right",
RT_IMG_TITLEINSERT=>"Image adding",
RT_IMG_SELECTFILE=>"Select image file to insert. File must has .JPG extension. Filesize should be less than 2 MBytes",
RT_IMG_TOOLARGE=>"Too huge image size. Please optimize it for the web and try to upload again. Filesize should be less than 2 MBytes",
RT_IMG_BADTYPE=>"File should has .JPG extension",
RT_IMG_RESETSIZE=>"Reset to original image size",
RT_DYNAMIC_BIND_SAMPLE=>"[Here will be printed text publishing by other control]",
RT_EDITABLE_BY_OWNER=>"Users able to edit text if owning object that the text bound to",

TLINKLIST_ABOUT=>"Link list to the pages of current level",
LINKLIST_STYLE=>"Link list style",
LINKLIST_STYLE_SIMPLE=>"In one line. One link by other",
LINKLIST_STYLE_HORIZONTAL=>"Horizontally",
LINKLIST_STYLE_WIDELINE=>"Horizontally, expand to the width",
LINKLIST_STYLE_VERTICAL=>"Vertically",
LINKLIST_BEFORE=>"Text before links",
LINKLIST_AFTER=>"Text after links",
LINKLIST_BETWEEN=>"Text between links",
LINKLIST_P_CSSHREF=>"CSS link style",
TLINKLIST_PADDING=>"Padding in pixels",

THTMLLIB_ABOUT =>"Printing hardcoded HTML snippet. Snippets must be placed in the 'theme' folder and has this extension: '.lib.html'.
   Source code of snippets could contains set of blocks
   ---BLOCKBEGIN the_name_of_block---
     any html-code
   ---BLOCKEND---",
THTMLLIB_NOLIBFILEFOUND=>"Library file not found",
THTMLLIB_SELECT_ITEM=>"Choose block",
THTMLLIB_LIBNAME=>"Library file name withot extension (do not put '.lib.html')",

TSOCKET_SOCKETADDRESS=>"Socket address",

DRAWTEXT_FONTSTYLE=>"Theme font style",
DRAWTEXT_ASTEXT=>"Do not use image. Render as text",

BUTTON_RENDER_ASTEXT=>"Render text button instead image",
BUTTON_LINKTO=>"Path to document or URL to jump after click the button",

TPAGEBUTTONS_BINDTOCONTROL=>"Bind to multipage control",
TPAGEBUTTONS_STYLE=>"Page button style",
TPAGEBUTTONS_STYLE_SIMPLETEXT=>"Simple text or numbers",
TPAGEBUTTONS_STYLE_BUTTONS=>"Pages like buttons",
TPAGEBUTTONS_CAPTION_PAGES=>"pages: ",
TPAGEBUTTONS_CAPTION_PAGEPREV=>"prev",
TPAGEBUTTONS_CAPTION_PAGENEXT=>"next",
TPAGEBUTTONS_CAPTION_PAGELAST=>"last",

TBUTTON_CAPTION=>"The button",
TBUTTON_DESCRIPTION=>"Draws one button from the theme.",
TDRAWTEXT_CAPTION=>"Graphic text",
TDRAWTEXT_DESCRIPTION=>"Draw text as JPG, GIF or PNG using one of predefined text styles",
THTMLLIBRARY_CAPTION=>"HTML snippet",
THTMLLIBRARY_DESCRIPTION=>"Prints out HTM snippet from website library Snippets whould be placed in the theme folder and has suffix '.lib.html'. Each library file has more than one snippet marked as ---BLOCKBEGIN and ---BLOCKEND words in the start of the line",
TJSMENU_CAPTION=>"Drop down menu",
TJSMENU_DESCRIPTION=>"Drop down menu on JAVASCRIPT. Menu generated only once per user and keeping in 'files' folder. If menu frequentially changed set the 'Embed in page' checkbox. This prevent from caching",
TLINKLIST_CAPTION=>"Links to neghbour pages",
TLINKLIST_DESCRIPTION=>"Print link to neighbour pages which are in the same folder of web structure",
TPAGEBUTTONS_CAPTION=>"The multipage control page tabs",
TPAGEBUTTONS_DESCRIPTION=>"Prints buttons to a page numbers or names (TNewsBrowser,TProductsPage)",
TPATH_CAPTION=>"Path to the current page",
TPATH_DESCRIPTION=>"Prints out path to the current page from topmost element in website hierarchy of current context",
TRICHTEXT_CAPTION=>"Image, tables, formatted text",
TRICHTEXT_DESCRIPTION=>"Mostly used control for site text feeding. Uses paragraph formatting, table autoformatting. Also has image embedding with rescaling after post.",
TTEXT_CAPTION=>"Text label",
TTEXT_DESCRIPTION=>"Text label that prints out text published by other page control",

SETTING_RICHTEXTIMGLIMITS=>"When users upload an image in richtext editor the image will be resampled if greater that limit size",
SETTING_RICHTEXTIMAGESQUALITY=>"The quality of image file",
TVERTICALMENU_CAPTION=>"Hierarchical tree menu",
TVERTICALMENU_DESCRIPTION=>"Displays link to pages as vertical menu with subtree",

TCOLUMNS_CAPTION=>"Columns",
TCOLUMNS_DESCRIPTION=>"Divides slot to columns",
TCOLUMNS_STYLE=>"Column style (one of theme style from section 'ColumnStyles')",
TCOLUMNS_COUNT=>"Number of columns",
TCOLUMNS_PADDING=>"Padding inside column",
TCOLUMNS_WIDTHS=>"Comma separated pixels or percents of column widths",
VERTICAL_SEPARATOR_STYLE=>"Vertical separator style",
TCOLUMNS_HEADER_COLORS=>"Comma-separated list of header colors, i.e. green,#0000ff,red",
TCOLUMNS_COLUMN_COLORS=>"Comma-separated list of column colors, i.e. #f0ffff,#fffff8,#f8f8f8",
TCOLUMNS_SHOW_HEADER=>"Show columns header",
);

?>
