<?
$GLOBALS['_STRINGS']['mship']=array(
MSHIP_TITLE=>"Memsbership system",
TITLE_MYOFFICE=>"My office",
TITLE_MEMBERS_CATALOGUE=>"Members catalogue",
ROLE_MODERATOR=>"Moderator",

IMEMBERS_UPDATE=>"Update data",
IMEMBERS_HIDE=>"Hide selected",
IMEMBERS_SHOW=>"Unhide selected",
IMEMBERS_MOVETO=>"Move to section ",
IMEMBERS_NEWANDHIDDEN=>"New and hidden members",

MEMBERS=>"Members",
MEMBER_SELECT_YOUR_SECTION=>"Select membership section for your profile",
MEMBER_CATALOGSECTION=>"Membership section",
MEMBER_CATALOGSECTIONS=>"Membership sections",
MEMBER_CATALOGSECTIONVISIBILITY=>"Membership section visibility",
MEMBER_PREFERRED_SECTION=>"Preferred name for your section",
MEMBER_NAME=>"Company name",
MEMBER_SUBTITLE=>"Subtitle",
MEMBER_STREETADDRESS=>"Description",
MEMBER_PHONE=>"Phone",
MEMBER_EMAIL=>"Email",
MEMBER_WEBSITE=>"Website",
MEMBER_CONTACTPERSON=>"Contact person",
MEMBER_SHOW=>"Show member",
MEMBER_OWNERUSERID=>"User login",
MEMBER_REMOVED=>"Removed by user",

TMYOFFICE_CAPTION=>'User office',
TMYOFFICE_DESCRIPTION=>'User profiles, albums, texts and other',
TMEMBERSLIST_CAPTION=>'Prints list of members',
TMEMBERSLIST_DESCRIPTION=>'Prints only registered and approved to show members. Also it shows profiles that watching user have made.',
TMEMBER_CAPTION=>'Publish member details ',
TMEMBER_DESCRIPTION=>'Publish information on layout using PageID as MemberID',

CREATE_TEXT_ABOUT=>"Create the text about this profile",
EDIT_TEXT_ABOUT=>"Edit the text about this profile",
CREATE_PHOTOALBUM=>"Create photo album",
EDIT_PHOTOALBUM=>"Open photo album",
CREATE_MYPROFILE=>"Create my profile",
VIEW_DETAILS=>"View details",
ADD_PROFILE=>"Add profile",
EDIT_PROFILE=>"Edit profile",
REMOVE_THIS_PROFILE=>"Remove this profile",
PROFILE_IS_PUBLISHED=>"This profile is published",

INPUT_NEW_CATEGORY=>"If your category not listed in our catalogue please enter preffered category name",
WARNING_NOTSELECTEDCATEGORY=>"You have not selected catalog category",
WARNING_NOPROFILENAME=>"You've not entered profile name",
WARNING_REGISTER_FIRST=>"You will be able to edit your profiles only after registration",
PROFILE_UNDER_REVIEW=>"This profile is under review",
PROFILE_UNDER_REVIEW_HINT=>"After you sending your representative profile it will be queued to review by manager. Profile will be activated after reviewing.",

MEMBERS_CATALOG_CONTEXT=>"Members catalogue system context",
MEMBER_CONTEXT=>"A member page system context",
HINT_REGISTERING_MEMBER=>"All new members registering on the site are hidden until administrator set 'Show member' to 'yes'",

MEMBERSTATE_HIDDEN=>"Hidden member",
MEMBERSTATE_VISIBLE=>'Visible member',
MEMBERSTATE_SELF_DELETED=>'Self-deleted member',
);
?>
