<?
$GLOBALS['_STRINGS']['img']=array(
TITLE=>"Image albums",
TIMGINDEX_ABOUT=>"Per page image gallery displaying",
P_BINDTO=>"the object the images refer to",
TIMGINDEX_P_COLUMNCOUNT=>"The number of columns. Set 0(zero) to auto size",
TIMGINDEX_P_TN_FORMAT=>"the saved images' format to be shown in the table",
TIMGINDEX_P_SHOWCAPTIONS=>"Show image subscriptions",
TIMGINDEX_T_SAVEMEFIRST=>"You can add images right after saving this element",
SELECT_GLOBAL_ALBUM=>"Global image album",
SELECT_EMPTY_IMAGE=>"Select image in current skin to be output instead empty image",
ADD_NEW_IMAGE=>"Add image",
IMAGE_ALIGNMENT=>"Image position",
ALIGN_LEFT=>"Left",
ALIGN_RIGHT=>"Right",
ALIGN_CENTER=>"Center",
ALIGN=>"Horisontal position",
TIMGINDEX_MSG_DYNAMICMODE=>"You cannot edit contents because the images related to another object will be stored here",
IMGVIEW_CONTEXT=>"Virtual section used for full size image displaying",

TN_FORMAT=>"Thumbnail format",
TIMGCONTAINER_ABOUT=>"Container for storing the images on the webpage",
ORIGINAL=>"Saved image",
MAXIMGSIZE=>"Max size of the saved image",

TIMAGE_C_ZOOMABLE=>"Show full size image on click",

IMAGE_P_ONSHOW=>"On click, the image can be opened in a new window and it can be shown in the monitor of the designated images",
IMAGE_V_ONSHOW_MODALWINDOW=>"Display image in phpsb modal window",
IMAGE_V_ONSHOW_WINDOW=>"Display image in popup window",
IMAGE_V_ONSHOW_IMGMONITOR=>"Display image in the image monitor",
IMAGE_V_ONSHOW_NEWBLANKWINDOW=>"Display image in new blank browser window",
IMAGE_V_ONSHOW_OPENCONTEXT=>"Forward user to image page in ImgViewContext",
IMAGE_V_ONSHOW_OPENCONTEXT_MODALWINDOW=>"Open modal window within image in ImgViewContext",
IMAGE_V_ONSHOW_OPENCONTEXT_BLANK=>"Open new window in ImgViewContext",
IMAGE_V_ONSHOW_NONE=>"nothing",
IMAGE_TARGETURL=>"Link to the web site or a site page to be opened for user on thumbnail click",
P_BINDTOMONITOR=>"If a page has a monitor, select it for displaying full size images",

ERROR_TOO_LARGE_FILE=>"File size excedes upload limit. Resize the image before sending.",
ERROR_DURING_UPLOAD=>"File sending error. Try again",
ERROR_NOT_IMAGE=>"Incorrect file type. It should be an image file or should be reconverted to jpg/gif/png file. Some JPEG types (i.e. in CMYK mode) are unsupported by system",
ERROR_NOT_JPEG=>"Only jpeg files can be sent. You have sent",
ERROR_BINDTO=>"Incorrect parent object reference",
ERROR_OBJECTPATH=>"Incorrect path to image object",

IMAGE_REGENERATE=>"Regenerate",
IMAGE_REMOVE=>"Remove selected",
IMAGE_DUMMYCAPTION=>"Click here to upload image",


TIMAGE_ABOUT=>"Single image with description",
TIMAGE_P_BINDTOOWNER=>"Object has a related image",
TIMAGE_CAPTION=>"Image",
TIMAGE_LABEL=>"Image label",
TIMAGE_ORDERNO=>"Image ordering number",
P_CSS_BORDER=>"Image frame style",
P_CSS_HREF=>"Link style",
WATERMARK_FILE=>"Corner watermark style",
IIMAGE_CLICK_BROWSE_TOADDNEW=>"Click 'Browse...' and select a new image",
IIMAGE_CLICK_BROWSE_TO_UPDATE=>"To replace the image by another one, click 'Browse...' and select a new image",
TIMAGE_C_DRAWIMAGE_ASIS=>"Draw image as is (without thumbnail)",
TIMAGE_WRITEFILE_ERRROR=>"Write error. No file write permissions",
TIMAGE_C_THUMBNAILDIMENSIONS=>"Image thumbnail dimensions",
TIMAGE_C_FIT_TO_THUMBNAIL=>"Image is trunkated to thumbnail size format",
TIMAGE_MAX_DIMENSIONS=>"Max dimensions of the saved image",
TIMAGE_IMG_BOUNDARY_WARNING=>"Server stores the initial image in addition to thumbnails.
   In order to save fit the max file size limit, the image will be downsized automatically",

TIMAGE_CLOSEPREVIEW=>"Close window",
TIMAGE_UNKNOWN_OBJECT=>"No object indicated for binding new ones",
TIMAGE_BAD_BINDING=>"Incorrect binding object'img.BindToOwner'",
TIMAGE_EDITCONTENT=>"Insert image",

ACCESS_POSTIMAGES=>"Image editing",

IMGCONTAINER_SOCKET=>"Image container contents",
IMGCONTAINER_EDITCONTENT=>"Edit image",
IMGCONTAINER_CONTROLINTRO=>"Images container. Contains images of the following formats:",
TIMGMONITOR_ABOUT=>"Image displaying monitor",
IMGMONITOR_CAPTIONINSIDE=>"Text shown inside the monitor, when no image is not selected",
IMGMONITOR_SIZE=>"Monitor size",
IMGMONITOR_FITINSIDE=>"Downsize images larger that the object selected",
IMGMONITOR_SHOWFORMAT=>"Image format to be displayed inside the monitor",
IMGMONITOR_CAPTIONINSIDE_SAMPLE=>"Select an image and click it",

TIMGDETAILS_ABOUT=>"Image information loader",
TIMGDETAILS_CAPTION=>"Image details",
TIMGDETAILS_THEIMAGE=>"Image",
TIMGDETAILS_BINDTO=>"Viewing image socket",


MENU_IMAGES=>"Images",
IMG_ALBUMS=>"Website images",
IMG_ALBUMCONTEXTS=>"Object image albums",
IMG_IMAGEFORMATS=>"Image formats",

SELECT_THUMBNAIL_TO_VIEW=>"Select thumbnail to view",

TIMAGE_DESCRIPTION=>'Placing this control onto layout you may select image on each page from selected album',
TIMGDETAILS_CAPTION=>'Image caption',
TIMGDETAILS_DESCRIPTION=>'Loads information about image. Image id is a page id of virtual context',
TIMGINDEX_CAPTION=>'Image index',
TIMGINDEX_DESCRIPTION=>'Prints out images that bound to target object. Target is one of the sockets that presents in the page (TNewsEvent:Header, TNewsEvent:Gallery, TProduct e.t.c.)',
TMONITOR_CAPTION=>'Image monitor',
TMONITOR_DESCRIPTION=>'Used within TImgIndex. Show image directly on the page. User do not leave current page clicking on the image thumbnail in the index.',


IMG_FORMAT_NAME=>"Thumbnail format name",
IMG_FORMAT_NONE=>"No change",
IMG_FORMAT_CROP=>"Crop image by borders",
IMG_FORMAT_FIT=>"Fit inside borders",
IMG_FORMAT_COLOR=>"Place inside border and fill bgColor around",
IMG_FORMAT_IMG=>"View other uploaded image file instead",
IMG_FORMAT_TN_ORIGINAL=>"Original image",
IMG_FORMAT_TN_FORMATNO=>"Thumbnail #",
IMG_FORMAT_RECOMMENDATION=>"Recommended sizing option for original format is 'fit' 800x600",
IMG_FORMAT_RESIZEOPTION=>"Resize option",
IMG_FORMAT_SIZE=>"Size (width x height)",
IMG_FORMAT_BGCOLOR=>"Background color",
IMG_FORMAT_WATERMARKFILE=>"Watermark image file",
IMG_FORMAT_CONVERTTO=>"Convert format to",

IMAGEALBUM_ADDNEW=>"Add new album",
IMAGEALBUM_NAME=>"Album name",
IMAGEALBUM_OPEN=>"Open an album",
IMAGEALBUM_DESCRIPTION=>"Description",
CHANGE_IMAGE_FORMAT=>"Change image format",
CHOOSE_IMAGE_FORMAT=>"Choose image format",
DONT_FORGET_TO_REGENERATE=>"Do not forget to regenerate images after changing format",
EMPTY_ALBUM=>"Empty album",
IMAGES_INSIDE=>"images inside",
CHOOSE_THUMBNAIL_FORMAT=>"Choose saved thumbnail format",
);
?>

